### ISSUE TITLE
Identity screen crash when feed not synchronised

### ISSUE THREAD

**Issue by howleysv** [MainframeHQ/js-mainframe#253]
I think the GraphQL schema just needs to handle the `feedHash` being null

**Comment by diogoperillo** [comment]
I thin this is resolved right @howleysv ?

**Comment by howleysv** [comment]
I reckon it will still happen if you're offline when you do onboarding
